Console.WriteLine("Введите число A");
int numA = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите число B");
int numB = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите число C");
int numC = Convert.ToInt32(Console.ReadLine());
int result = numA;
if (numB > result) result = numB;
if (numC > result) result = numC;
Console.WriteLine($"Максимальное число {result}");